apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemonset
spec:
  selector:
    matchLabels:
      name: mydaemon
  template:
    metadata:
      labels:
        name: mydaemon
    spec:
      containers:
        - name: mydaemon-container
          image: nginx
          ports:
            - containerPort: 80