apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-node-secretcm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-node-secretcm
  template:
    metadata:
      labels:
        app: mi-node-secretcm
    spec:
      containers:
      - name: mi-node-secretcm
        image: tu_usuario_dockerhub/secretcm:latest
        ports:
        - containerPort: 30091
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: apiUrl
        - name: API_TOKEN
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: apiToken
---
apiVersion: v1
kind: Service
metadata:
  name: mi-node-app-service
spec:
  type: LoadBalancer
  selector:
    app: mi-node-secretcm
  ports:
    - port: 80
      targetPort: 30091              