apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion-nodejs # Nombre del deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-aplicacion-nodejs
  template:
    metadata:
      labels:
        app: mi-aplicacion-nodejs
    spec:
      containers:
      - name: mi-aplicacion-nodejs # Mi contenedor
        image: nginx:latest
        ports:
        - containerPort: 30090 # Puerto del contenedor