 apiVersion: v1
 kind: Pod
 metadata:
  name: mypod
 spec:
  containers:
  - name: mycontainer1
    image: nginx:alpine
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  - name: mycontainer2
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {}